= Connect to a Couchbase Server Cluster
:description: It's easy. You'll be an expert in no time.
:navtitle: Connecting
:page-topic-type: howto
:example-source: 3.2@java-sdk:howtos:example$Queries.java
include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

Use the https://docs.couchbase.com/sdk-api/couchbase-kotlin-client/kotlin-client/com.couchbase.client.kotlin/-cluster/-companion/connect.html[`Cluster.connect`] companion factory method to create a https://docs.couchbase.com/sdk-api/couchbase-kotlin-client/kotlin-client/com.couchbase.client.kotlin/-cluster/[`Cluster`].

It's best to create a single Cluster when your application starts up, and share it across your application.
When your application shuts down, disconnect the Cluster.
Disconnecting gives any in-flight requests a chance to complete, then releases the resources managed by the Cluster.


[source,kotlin]
----
include::example$Connect.kt[]
----
<1> The Kotlin SDK uses https://kotlinlang.org/docs/coroutines-overview.html[coroutines] for asynchronous execution.
Many of the methods in the SDK are suspending functions, and can only be called from a coroutine context.
The https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/run-blocking.html[runBlocking] method is a convenient way to create a coroutine context in a main method, in test code, or in some other blocking context, but should never be called from within another coroutine.

<2> `Cluster.connect` returns immediately.
The SDK continues working in the background to finish connecting.
Waiting for the connection to complete is optional, but can be good because it lets you know right away if there's a problem with the connection.
Waiting here also makes it less likely a following request will time out, since none of the time allotted to the next request will be wasted waiting for the connection to complete.

[#connection-string]
== Connection string

The SDK needs to know the address of at least one node in the Couchbase Server cluster; it will discover the others.
The simplest connection string is a single hostname or literal IP address, like `"foo.example.com"` or `"127.0.0.1"`.

With DNS SRV, one address is enough.
The SDK uses the address to look up the DNS SRV record, then inspects the record to learn the addresses of all the nodes.

NOTE: Couchbase Capella always uses DNS SRV.

If you're not using DNS SRV, it's good to include the addresses of multiple nodes in the connection string.
The more addresses you provide, the more likely the SDK will be able to connect when some nodes are unavailable.
To specify multiple addresses, join them with commas:

.Connection string with two addresses
[source,kotlin]
----
"foo.example.com,bar.example.com"
----

[#connection-string-ports]
=== Non-standard ports

By default, the Couchbase Key Value (KV) service listens on port 11210 (or 11207 for TLS), and the Manager service listens on port 8091 (or 18091 for TLS).
The SDK can bootstrap against either service, but the KV service is preferable because it's faster.

If the server is listening on a non-default port, or there's some kind of port mapping going on, include the port in the connection string:


.Connection string with non-standard KV port
[source,kotlin]
----
"foo.example.com:1234"
----

If you need to bootstrap against a custom manager port (because the node isn't running the KV service), tell the SDK it's a manager port by appending "=manager", like this:

.Connection string with non-standard manager port
[source,kotlin]
----
"foo.example.com:4567=manager"
----

[#connection-string-params]
=== Connection string parameters

Connection strings have one more trick up their sleeve: they can configure the SDK's behavior.

We mentioned DNS SRV earlier.
Let's suppose for some reason you need to tell the SDK not to use DNS SRV.
There are few different ways to do that, but since we're talking about connections strings...

.Connection string with a parameter
[source,kotlin]
----
"foo.example.com?io.enableDnsSrv=false"
----

.Connection string parameters don't like sharing
WARNING: If the `Cluster` uses a shared `ClusterEnvironment`, any parameters in the connection string will be ignored.
Environment sharing is an advanced topic we'll cover later.

To include multiple parameters, join them with `&`, like:

.Connection string with two parameters
[source,kotlin]
----
"foo.example.com?io.enableDnsSrv=false&timeout.kvTimeout=5s"
----

.Is the connection string a URI?
TIP: You may prefix the string with `couchbase://` or `couchbases://`, but the SDK doesn't mind if the prefix is absent.
It will, however, complain if you use the `couchbases://` prefix and neglect to configure the required TLS settings.
