= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase Kotlin SDK
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:navtitle: Compatibility

[abstract]
{description}

The Kotlin SDK requires Java 8 or later, and Kotlin 1.6.20 or later.

[#couchbase]
== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Kotlin SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="50,50"]
|===
| | SDK 1.0

| *Server 5.0-5.5*
| *✖*

| *Server 6.0-6.5*
| *✔*

| *Server 6.6*
| *✔*

| *Server 7.0-7.1*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

At time of release, the Couchbase 1.0 Kotlin SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the 1.0 SDK includes the Capella client certificate ready installed.


[#jdk-compat]
== JDK Version Compatibility

The Kotlin SDK is tested with Oracle JDK and OpenJDK.
Other JDK implementations might work but are not tested and are unsupported.
We recommend running the latest LTS version with the highest patch version available.

We only support LTS versions of Oracle JDK and OpenJDK.
Other versions may work -- _but they are not tested and they are not supported_.

The following JDK releases are supported:

* https://adoptium.net/[OpenJDK 11] (Hotspot recommended) or https://www.oracle.com/java/technologies/downloads/#jdk11[Oracle JDK 11]
* https://adoptium.net/[OpenJDK 17 with HotSpot JVM] (recommended)
* https://www.oracle.com/java/technologies/downloads/#jdk17[Oracle JDK 17 (recommended)]
* https://adoptium.net/[OpenJDK 1.8 with HotSpot JVM]
* https://www.oracle.com/java/technologies/downloads/#java8[Oracle JDK 1.8]

Please make sure you run on one of the latest patch releases, since they provide stability improvements and security fixes in general.

[#os]
== OS Compatibility

In general, the JVM eliminates concerns about underlying OS compatibility, 
and Couchbase JVM SDKs can be expected to run on all of the Operating Systems supported by xref:7.0@server:install:install-platforms.adoc[Couchbase Server].
The JVM SDKs should also be expected to run on other commonly-available GNU/Linux distributions which support an appropriate JDK, but not all combinations can be tested -- notable exceptions are listed below.

[#alpine]
=== Alpine Linux Compatibility

The https://netty.io[Netty] I/O library used by our JVM SDKs supports native optimizations to achieve higher throughput and lower latency 
-- which the SDK enables by default. 
Those modules are compiled against `glibc` and Alpine Linux uses `musl` instead --
so the Java SDK is unable to complete bootstrapping on this platform.

Because Alpine Linux does not have the `glibc` support needed,
we highly recommend that you seek an alternative distribution where possible. 
If that is not a option, then a possible workaround that can be applied is as follows:

* Disable the native IO:
+
[source]
----
val cluster = Cluster.connect(...) {
    ioEnvironment {
        enableNativeIo = false
    }
}
----

* Disable it in Netty itself via the following system property:
+
[source]
----
-Dcom.couchbase.client.core.deps.io.netty.transport.noNative=true
----

The downside of these workarounds is potentially reduced performance, which can be determined through benchmarking and profiling.


//== Couchbase Feature Availability Matrix
//
//.Couchbase Server and SDK Supported Version Matrix
//[.table-merge-cells]
//[cols="7,7,5,6,5"]
//|===
//| | Server 5.0, 5.1, & 5.5 | Server 6.0 | Server 6.5 & 6.6 | Server 7.0
//
//| Enhanced Durability
//4+| All SDK versions
//
//| Durable Writes
//2+| Not Supported
//2+| Since 3.0
//
//| Analytics
//| DP in 5.5 with 2.6
//3+| Since 2.7
//
//| Distributed ACID Transactions
//2+| Not Supported
//2+| Since 3.0footnote:[3.0.7 or more recent recommended; preferably, follow the transitive dependency for the transactions library in Maven.]
//
//| N1QL Queries inside the Transaction Lambda
//3+| Not Supported
//| Since 3.0.7footnote:[With Java Transactions Library 1.1.3 -- but Java Transactions Library 1.2.1 or newer recommended.]
//
//| Default Collections
//2+| Not Supported
//| Developer Preview in 6.5-6.6, SDK 3.0
//| Since 3.0.6
//
//| Scope-Level N1QL Queries & all Collections features
//3+| Not Supported
//| Since SDK 3.2.0
//
//| Field Level Encryption v2
//2+| Not Supported
//2+| Since SDK 3.0.5footnote:[Field Level Encryption distributed as separate library.]
//
//| Request Tracing
//2+| Not Supported
//2+| Since SDK 3.1.0
//|===

include::7.1@sdk:shared:partial$network-requirements.adoc[]

include::7.1@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

include::7.1@sdk:shared:partial$api-version.adoc[tag=api-version]
