= Couchbase Kotlin SDK Release Notes and Archives
:description: Release notes for the Couchbase Kotlin Client.
:navtitle: Release Notes
:page-topic-type: project-doc
:page-partial:

// tag::all[]
[abstract]
{description}


[[v1.0.4]]
== Version 1.0.4 (9 September 2022)

This maintenance release adds more cluster management APIs, and updates dependency versions.

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.0.4/index.html[API Reference]

=== Improvements

* https://issues.couchbase.com/browse/KCBC-94[KCBC-94]:
`UserManager` has a new `changePassword` function that lets you change the password of the currently authenticated user.

* https://issues.couchbase.com/browse/KCBC-99[KCBC-99]:
`Bucket` has a new `collections` property of type `CollectionManager`.
You can use the collection manager to create and delete scopes and collections.
(Requires Couchbase Server 7.0 or later.)

* https://issues.couchbase.com/browse/KCBC-100[KCBC-100]:
Added two new global config properties to help diagnose leaked Cluster instances.
`Cluster.maxAllowedInstances` is the number of connected Cluster instances that may exist at the same time.
Calling `Cluster.connect` after this limit is reached will either fail or log a warning, depending on the value of the new `Cluster.failIfInstanceLimitReached` property.
The default values log a warning if more than 1 Cluster is connected at a time.

* https://issues.couchbase.com/browse/JVMCBC-1134[JVMCBC-1134]:
Updated `MemcachedProtocol::decodeStatus` to be inlineable.

* https://issues.couchbase.com/browse/JVMCBC-1135[JVMCBC-1135]:
Moved `Core#reconfiguration` off IO threads.

* https://issues.couchbase.com/browse/JVMCBC-1143[JVMCBC-1143]:
Failed telemetry spans will now record their exception and error status.

* https://issues.couchbase.com/browse/JVMCBC-1145[JVMCBC-1145]:
Updated maintenance dependencies.


[[v1.0.3]]
== Version 1.0.3 (2 August 2022)

Maintenance release.

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.0.3/index.html[API Reference]

=== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1116[JVMCBC-1116]:
Dependency versions have been increased.

=== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-1119[JVMCBC-1119]:
The num (kv) nodesExt to equal number of nodes check can lead to otherwise healthy clusters being flagged as not ready.
The check has been removed, and now `bucket.waitUntilReady` will not time out on these edge cases.
* https://issues.couchbase.com/browse/JVMCBC-1120[JVMCBC-1120]:
`ClusterConfig#allNodeAddresses` now takes global config into account -- avoiding the triggering of some unnecessary reconfigurations.
* https://issues.couchbase.com/browse/JVMCBC-1112[JVMCBC-1112]:
Deprecated Reactor Processors have been replaced.
* https://issues.couchbase.com/browse/JVMCBC-1115[JVMCBC-1115]:
The SDK now allows for configurations with _only_ TLS ports.


[[v1.0.2]]
== Version 1.0.2 (6 July 2022)

Maintenance release.

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.0.2/index.html[API Reference]

=== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-1103[JVMCBC-1103]:
To reduce overhead, the `MAX_PARALLEL_FETCH` value in `KeyValueBucketRefresher` has been updated to only fetch one config per poll interval.

* https://issues.couchbase.com/browse/JVMCBC-1104[JVMCBC-1104]:
Fixed issue where the global refresher did not honor the config poll interval.


[[v1.0.1]]
== Version 1.0.1 (8 June 2022)

Maintenance release.

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.0.1/index.html[API Reference]

=== Improvements

* https://issues.couchbase.com/browse/KCBC-79[KCBC-79]:
`JacksonJsonSerializer` now accepts the jackson `ObjectMapper` which for example makes it easier to use out of the box with Spring Boot.

* https://issues.couchbase.com/browse/JVMCBC-1093[JVMCBC-1093]:
Previously, when a DNS SRV lookup failure occurred, the SDK logged this as a `WARNING` along with a stack trace.
The lookup failure is typically harmless, so the log message has now been downgraded to `INFO` level, without a stack trace.

* https://issues.couchbase.com/browse/JVMCBC-1088[JVMCBC-1088]:
Updated Netty to version `4.1.77.Final`.


[[v1.0.0]]
== Version 1.0.0 (3 May 2022)

Initial GA release.

//== Older Releases
//
//Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
// end::all[]
