= SDK Release Notes
:description: Release notes for the Couchbase Kotlin Client.
:navtitle: Release Notes
:page-toclevels: 2
:page-topic-type: project-doc
:page-partial:

// tag::all[]
[abstract]
{description}



[#latest-release]
== Kotlin SDK 1.2 Releases

We always recommend using the latest version of the SDK -- it contains all of the latest security patches and support for new and upcoming features.
All patch releases for each dot minor release should be API compatible, and safe to upgrade;
any changes to expected behavior are noted in the release notes that follow.


[[v1.2.1]]
=== Version 1.2.1 (7 December 2023)

This is a regular maintenance release.

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.2.1/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.5.1/[Core API Reference]


==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1435[JVMCBC-1435],
https://issues.couchbase.com/browse/JVMCBC-1436[JVMCBC-1436]:
Upgraded Netty and Jackson dependencies.
* https://issues.couchbase.com/browse/JVMCBC-1440[JVMCBC-1440]:
Adding `DocumentNotLockedException` supporting future Couchbase Server versions that will return an error code when unlocking a document that is not locked.

==== Bugfixes

* https://issues.couchbase.com/browse/JVMCBC-1433[JVMCBC-1433]:
The SDK can now connect to Memcached buckets whose names contain the percent (`%`) character.
(We'd like to take this opportunity to remind everyone that Memcached buckets are deprecated in favor of Ephemeral buckets.)
* https://issues.couchbase.com/browse/JVMCBC-1437[JVMCBC-1437]:
With Couchbase Server versions that support updating a collection's max expiry, it's now possible to clear the expiry by passing `Duration.ZERO` for the new value.
* https://issues.couchbase.com/browse/JVMCBC-1441[JVMCBC-1441]:
The SDK now handles an additional error case for `IndexNotFoundException`.
* https://issues.couchbase.com/browse/JVMCBC-1442[JVMCBC-1442]:
Fixed a dependency issue with `tracing-opentelemetry` module.




[[v1.2.0]]
=== Version 1.2.0 (21 November 2023)

The SDK now supports the new couchbase2 protocol, which is upcoming in future Couchbase Server versions.
It can be enabled through using a connection string starting with `couchbase2://`.
Please see xref:howtos:connecting.adoc#cloud-native-gateway[Cloud Native Gateway] for more information.

The SDK now directly depends on SLF4J, which may impact some users -- see below for details.

==== API Impacting

When upgrading from a previous version of the SDK, please be aware of this behavioral change:

[CAUTION]
====
https://issues.couchbase.com/browse/JVMCBC-1319[JVMCBC-1319]:
As https://www.couchbase.com/forums/t/embracing-slf4j-in-couchbase-java-sdk-3-5/36474[previously announced], the SLF4J API is now a required dependency, and the SDK does all logging through SLF4J.
The following client settings for customizing logging behavior are deprecated, and no longer have any effect:

** `logger.disableSlf4J`
** `logger.fallbackToConsole`
** `logger.consoleLoggerFormatter`

If your project does not already use SLF4J, please follow the announcement link for details and a mini-migration guide.
====

==== Improvements

* https://issues.couchbase.com/browse/KCBC-132[KCBC-132]:
`BucketManager` and `CollectionManager` now know about the history preservation settings added in Couchbase Server 7.2.
+
`CollectionManager` has a new `updateCollection` method for changing the settings of an existing collection.
Note that updating a collection's `maxExpiry` setting requires Couchbase Server 7.6.

* https://issues.couchbase.com/browse/JVMCBC-1402[JVMCBC-1402],
https://issues.couchbase.com/browse/JVMCBC-1410[JVMCBC-1410]:
Upgraded Netty from 4.1.96 to 4.1.100, and upgraded `OpenTelemetry` dependency.

* https://issues.couchbase.com/browse/JVMCBC-1430[JVMCBC-1430]:
Optimization: removed creation of unnecessary metrics labels when default `LoggingMeter` is used.

* https://issues.couchbase.com/browse/JVMCBC-1391[JVMCBC-1391]:
The Bucket Manager API is now forward-compatible with future versions of Couchbase Server that might support storage engine types other than "magma" and "couchstore".

* https://issues.couchbase.com/browse/JVMCBC-1327[JVMCBC-1327]:
Improved support for failover handling in future server versions.

==== Bugfixes

* https://issues.couchbase.com/browse/KCBC-139[KCBC-139]:
When using `BucketManager` with Couchbase Server Community Edition, specifying a bucket creation argument not supported by Community Edition now always results in a `FeatureNotAvailableException`.
Previously, this exception was thrown only if the argument differed from the default.

* https://issues.couchbase.com/browse/JVMCBC-1264[JVMCBC-1264]:
DNS SRV lookups now honor the DNS search path.
This enables DNS SRV resolution in Kubernetes environments where the `*-srv` hostname advertised by the Couchbase Operator is a partial name that must be resolved using a suffix from the DNS search path.

* https://issues.couchbase.com/browse/JVMCBC-1426[JVMCBC-1426]:
When Couchbase Server is too busy to start a new KV range scan, the SDK now retries instead of throwing a `CouchbaseException`.


== Kotlin SDK 1.1 Releases

[[v1.1.11]]
=== Version 1.1.11 (4 October 2023)

This is a regular maintenance release.

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.1.11/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.11/[Core API Reference]


==== Improvements
* https://issues.couchbase.com/browse/JCBC-2046[JCBC-2046]:
With thanks to community member https://github.com/marcingrzejszczak[Marcin Grzejszczak] for the contribution, support for Micrometer Observation has been added to all JVM SDKs via the new `tracing-micrometer-observation` module.
* https://issues.couchbase.com/browse/JVMCBC-1327[JVMCBC-1327]:
Internal improvements to support upcoming faster failover and config push features.

==== Bugfixes
* https://issues.couchbase.com/browse/JVMCBC-1364[JVMCBC-1364]:
Fixed decoding of certain niche sub-document errors, so they no longer raise a `DecodingFailureException`.



[[v1.1.10]]
=== Version 1.1.10 (6 September 2023)

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.1.10/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.10/[Core API Reference]

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1367[JVMCBC-1367]:
The `db.couchbase.operations` metric now has `db.name` (bucket), `db.couchbase.scope`, `db.couchbase.collection` and `outcome` labels (tags).
This new feature is at Stability.Volatile, and may change before it is promoted to Stability.Committed in a future release.
* https://issues.couchbase.com/browse/JVMCBC-1311[JVMCBC-1311],
https://issues.couchbase.com/browse/JVMCBC-1352[JVMCBC-1352]:
Upgraded dependencies.

==== Bugfixes
* https://issues.couchbase.com/browse/JVMCBC-1350[JVMCBC-1350]:
`lookupInAnyReplica` now throws `FeatureNotAvailableException` if the server does not support the feature.
* https://issues.couchbase.com/browse/JVMCBC-1351[JVMCBC-1351]:
`lookupInAnyReplica` no longer hangs when too many operations are specified.
* https://issues.couchbase.com/browse/JVMCBC-1353[JVMCBC-1353]:
Removed the unrelocated `io.opentracing` classes that accidentally slipped into version 2.4.9 of the Couchbase `core-io` library.
* https://issues.couchbase.com/browse/JVMCBC-1361[JVMCBC-1361]:
When the SDK receives multiple cluster map versions at the same time, it is now more careful about applying only the most recent version.
Before this change, there was a brief window where the SDK could apply an obsolete cluster map.
If this happened, the SDK would temporarily dispatch requests to incorrect or non-existent nodes.
This condition was typically short-lived, and healed the next time the SDK polled for an updated cluster map, or dispatched a KV request to the wrong node.
* https://issues.couchbase.com/browse/JVMCBC-1368[JVMCBC-1368]:
Fixed a rare `java.lang.ArithmeticException: / by zero` exception in `RoundRobinSelectionStrategy.select` that could occur during rebalance.






[[v1.1.9]]
=== Version 1.1.9 (2 August 2023)

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.1.9/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.9/[Core API Reference]

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1339[JVMCBC-1339]:
When KV traffic capture is enabled, each `ReadTrafficCapturedEvent` now contains a single protocol frame, and the human-readable frame description is more accurate.
* https://issues.couchbase.com/browse/JVMCBC-1320[JVMCBC-1320]:
The `waitUntilReady` method is now more aggressive about retrying failed pings.
Also, waiting for a desired state of `DEGRADED` no longer fails when the client is fully connected to the cluster.
* https://issues.couchbase.com/browse/JVMCBC-1343[JVMCBC-1343]:
Reduced the default value for the `io.idleHttpConnectionTimeout` client setting to 1 second.
The previous default (4.5 seconds) was too close to the 5-second server-side timeout, and could lead to spurious request failures.


[[v1.1.8]]
=== Version 1.1.8 (19 July 2023)

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.1.8/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.8/[Core API Reference]

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1322[JVMCBC-1322]:
The `waitUntilReady()` method now logs additional diagnostic information to the `com.couchbase.core.WaitUntilReady` logging category at `DEBUG` level.


[[v1.1.7]]
=== Version 1.1.7 (12 June 2023)

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.1.7/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.7/[Core API Reference]

This release refines the sub-document counter methods, and adds a new connection string parameter for disabling TLS certificate verification.

==== Improvements

* https://issues.couchbase.com/browse/KCBC-123[KCBC-123]:
Added new versions of `MutateInSpec.incrementAndGet` and `decrementAndGet` without a `delta` parameter ("increment/decrement" implies the delta is 1).
Added a `MutateInSpec.addAndGet` method that takes a delta.
Deprecated the old increment/decrement methods that take a delta, in favor of the new `addAndGet` method.

* https://issues.couchbase.com/browse/JVMCBC-1290[JVMCBC-1290]:
Added a new client setting, `security.enableCertificateVerification`, which defaults to true.
This setting allows disabling TLS certificate verification in development environments where configuring the CA certificate to trust is not practical.
Setting this to false is equivalent to configuring the environment to use `InsecureTrustManager.INSTANCE`.
For compatibility with other modern Couchbase SDKs, certificate verification can now be disabled using the connection string parameter `tls_verify=none`.
This feature is introduced at stability level `Volatile`, meaning it may change in a patch release without notice.

* https://issues.couchbase.com/browse/JVMCBC-1278[JVMCBC-1278],
https://issues.couchbase.com/browse/JVMCBC-1310[JVMCBC-1310],
https://issues.couchbase.com/browse/JVMCBC-1313[JVMCBC-1313]:
Dependencies updated.


[[v1.1.6]]
=== Version 1.1.6 (4 May 2023)

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.1.6/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.6/[Core API Reference]

This is a regular maintenance release, with no notable changes apart from depedency version bumps.


[[v1.1.5]]
=== Version 1.1.5 (12 April 2023)

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.1.5/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.5/[Core API Reference]

This is a regular maintenance release.

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1223[JVMCBC-1223]:
Adds a `RetryReason.AUTHENTICATION_ERROR` at `Uncommitted` API stability level.
A custom `RetryStrategy` can use this new, more granular information to distinguish if a connection problem is down to an authentication issue.

==== Bug Fixes

* https://issues.couchbase.com/browse/KCBC-118[KCBC-118]:
Accessing the result of a sub-document lookupIn `exists` command now throws an appropriate exception (instead of returning false) in more cases where it's not possible to determine whether the field exists:
** If the document is not JSON, `DocumentNotJsonException` is thrown.
** If a user without the `SystemXattrRead` permission attempts to check the existence of a system XATTR, `XattrNoAccessException` is thrown.

* https://issues.couchbase.com/browse/JVMCBC-1252[JVMCBC-1252]:
Orphaned "observe" operations will no longer occasionally contain a `total_duration_us` field equal to 0.
* https://issues.couchbase.com/browse/JVMCBC-1255[JVMCBC-1255]:
If you were subscribing to the event bus and printing all the events, you may have noticed `Event.toString()` throwing a `NullPointerException` if the event context is null.
`Event.toString()` now handles null contexts more gracefully, and no longer throws this exception.


[[v1.1.4]]
=== Version 1.1.4 (8 March 2023)

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.1.4/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.4/[Core API Reference]

This is a regular maintenance release.

==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1237[JVMCBC-1237]:
Added "network" as an alias for the "io.networkResolution" connection string parameter.
For example, the connection string "couchbase://example.com?network=external" is now equivalent to "couchbase://example.com?io.networkResolution=external".
This was done for compatibility with other Couchbase SDKs that use "network" as the name of this parameter.

==== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-1232[JVMCBC-1232]:
`Cluster.connect()` now rejects connection strings that have no addresses (like "couchbase://").
Before this change, it would accept the invalid connection string, and subsequent operations would fail with a misleading error message: "The cluster does not support cluster-level queries".


[[v1.1.3]]
=== Version 1.1.3 (9 February 2023)

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.1.3/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.3/[Core API Reference]

This is a regular maintenance release.

==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1181[JVMCBC-1181]:
It is now possible to authenticate over secure connections even if the JVM does not support the SASL PLAIN authentication mechanism.
* https://issues.couchbase.com/browse/JVMCBC-1184[JVMCBC-1184]:
Updated dependencies.

==== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-1160[JVMCBC-1160]:
When a sub-document path has a syntax error or is inappropriate for an operation, the SDK now throws `PathInvalidException`.
Prior to this change, it would throw a generic `CouchbaseException` with the message "Unexpected SubDocument response code".


[[v1.1.2]]
=== Version 1.1.2 (16 January 2023)

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.1.2/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.2/[Core API Reference]

This is a regular maintenance release.

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1175[JVMCBC-1175]:
The SDK now includes native libraries for IO and TLS that can enhance performance on `aarch_64` architectures like Graviton and Apple Silicon.
Previously, native libraries were included only for `x86_64` architectures.
Native libraries for IO and TLS are enabled by default.
If you need to disable native IO, set the `ioEnvironment.enableNativeIo` client setting to false.
To disable native TLS, set the `security.enableNativeTls` client setting to false.

==== Bug Fixes
* https://issues.couchbase.com/browse/JVMCBC-1161[JVMCBC-1161]:
Fixed a minor issue where `cluster.disconnect()` could occasionally time out due to a race condition.

* https://issues.couchbase.com/browse/JVMCBC-1176[JVMCBC-1176]:
Setting `security.enableNativeTls` to false now prevents the SDK from even attempting to load the native TLS library.
(Prior to this change, the SDK would load the library and just not use it.)
In addition to saving a bit of memory, this prevents the JVM from segfaulting on Alpine Linux where glibc is not available.

* https://issues.couchbase.com/browse/JVMCBC-1174[JVMCBC-1174]:
Fixed a regression that prevented native TLS from being used regardless of whether the `security.enableNativeTls` client setting was set to true.


[[v1.1.1]]
=== Version 1.1.1 (7 December 2022)

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.1.1/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.1/[Core API Reference]

==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1163[JVMCBC-1163]:
Dependencies have been updated.

* https://issues.couchbase.com/browse/JVMCBC-1156[JVMCBC-1156]:
The traffic tracing functionality has been enhanced to perform Wireshark-style dissection of portions of the KV protocol.

* https://issues.couchbase.com/browse/JCBC-2021[JCBC-2021]:
Diagnostics for an endpoint now include the state of the endpoint's circuit breaker.

==== Bug Fixes

* https://issues.couchbase.com/browse/KCBC-107[KCBC-107]:
The logging configuration DSL property `enableDiagnosticContext` is now mutable.

* https://issues.couchbase.com/browse/JVMCBC-1157[JVMCBC-1157]:
The SDK no longer rejects a `PersistTo` requirement in a bucket using the Magma storage engine. Before this change, the SDK would refuse the request because it misidentified Magma buckets as ephemeral (unable to persist documents).

* https://issues.couchbase.com/browse/JVMCBC-1167[JVMCBC-1167]:
If you call `CancellationErrorContext.getWaitUntilReadyContext()` on an error context that didn't come from a "wait until ready" request, the method is now guaranteed to return null instead of sometimes throwing a `ClassCastException`.

* https://issues.couchbase.com/browse/JVMCBC-1178[JVMCBC-1178]:
Fixed a memory leak in `ManagerMessageHandler`.


[[v1.1.0]]
=== Version 1.1.0 (24 October 2022)

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.1.0/index.html[API Reference]
| http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.0/[Core API Reference]

==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1102[JVMCBC-1102]:
Added support for serverless execution environments including AWS Lambda.

* https://issues.couchbase.com/browse/KCBC-101[KCBC-101]:
Added an experimental JSON serializer backed by `kotlinx.serialization`.
See this https://github.com/couchbase/couchbase-jvm-clients/blob/c9ffa30f56294a0b82721bfa42f91e7bc7021bae/kotlin-client/src/main/kotlin/com/couchbase/client/kotlin/samples/KotlinxSerializationSamples.kt#L30-L43[sample code] for usage and caveats.

* https://issues.couchbase.com/browse/KCBC-102[KCBC-102]:
Added support for configuration profiles, which allow you to quickly configure an environment for common use-cases.
In particular, this makes it easy to apply timeouts appropriate for WAN (Internet) development, such as developing against a remote Couchbase Capella instance.
Example usage:
+
[source,kotlin]
----
val cluster = Cluster.connect(
    connectionString, username, password
) {
    applyProfile("wan-development")
}
----

* https://issues.couchbase.com/browse/KCBC-105[KCBC-105],
https://issues.couchbase.com/browse/JVMCBC-1144[JVMCBC-1144]:
If your Couchbase Server cluster's root certificate is signed by a well-known certificate authority whose certificate is included in the JVM's trust store, it's no longer necessary to configure the certificate in the securityConfig settings.

* https://issues.couchbase.com/browse/KCBC-104[KCBC-104]:
Changed `AuthenticationFailureException` error message to indicate that bucket hibernation is now a potential cause.
Bucket hibernation is a feature coming in a future Couchbase release.

* https://issues.couchbase.com/browse/JVMCBC-1154[JVMCBC-1154]:
Bumped dependencies.

==== Bug Fixes
* https://issues.couchbase.com/browse/JVMCBC-1141[JVMCBC-1141]:
Provide required OpenTelemetry span attributes.

* https://issues.couchbase.com/browse/JVMCBC-1155[JVMCBC-1155]:
Make sure targeted round-robin request keeps retrying if no config is available.


== Kotlin SDK 1.0 Releases


[[v1.0.4]]
=== Version 1.0.4 (9 September 2022)

This maintenance release adds more cluster management APIs, and updates dependency versions.

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.0.4/index.html[API Reference]

==== Improvements

* https://issues.couchbase.com/browse/KCBC-94[KCBC-94]:
`UserManager` has a new `changePassword` function that lets you change the password of the currently authenticated user.

* https://issues.couchbase.com/browse/KCBC-99[KCBC-99]:
`Bucket` has a new `collections` property of type `CollectionManager`.
You can use the collection manager to create and delete scopes and collections.
(Requires Couchbase Server 7.0 or later.)

* https://issues.couchbase.com/browse/KCBC-100[KCBC-100]:
Added two new global config properties to help diagnose leaked Cluster instances.
`Cluster.maxAllowedInstances` is the number of connected Cluster instances that may exist at the same time.
Calling `Cluster.connect` after this limit is reached will either fail or log a warning, depending on the value of the new `Cluster.failIfInstanceLimitReached` property.
The default values log a warning if more than 1 Cluster is connected at a time.

* https://issues.couchbase.com/browse/JVMCBC-1134[JVMCBC-1134]:
Updated `MemcachedProtocol::decodeStatus` to be inlineable.

* https://issues.couchbase.com/browse/JVMCBC-1135[JVMCBC-1135]:
Moved `Core#reconfiguration` off IO threads.

* https://issues.couchbase.com/browse/JVMCBC-1143[JVMCBC-1143]:
Failed telemetry spans will now record their exception and error status.

* https://issues.couchbase.com/browse/JVMCBC-1145[JVMCBC-1145]:
Updated maintenance dependencies.


[[v1.0.3]]
=== Version 1.0.3 (2 August 2022)

Maintenance release.

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.0.3/index.html[API Reference]

==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1116[JVMCBC-1116]:
Dependency versions have been increased.

==== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-1119[JVMCBC-1119]:
The num (kv) nodesExt to equal number of nodes check can lead to otherwise healthy clusters being flagged as not ready.
The check has been removed, and now `bucket.waitUntilReady` will not time out on these edge cases.
* https://issues.couchbase.com/browse/JVMCBC-1120[JVMCBC-1120]:
`ClusterConfig#allNodeAddresses` now takes global config into account -- avoiding the triggering of some unnecessary reconfigurations.
* https://issues.couchbase.com/browse/JVMCBC-1112[JVMCBC-1112]:
Deprecated Reactor Processors have been replaced.
* https://issues.couchbase.com/browse/JVMCBC-1115[JVMCBC-1115]:
The SDK now allows for configurations with _only_ TLS ports.


[[v1.0.2]]
=== Version 1.0.2 (6 July 2022)

Maintenance release.

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.0.2/index.html[API Reference]

==== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-1103[JVMCBC-1103]:
To reduce overhead, the `MAX_PARALLEL_FETCH` value in `KeyValueBucketRefresher` has been updated to only fetch one config per poll interval.

* https://issues.couchbase.com/browse/JVMCBC-1104[JVMCBC-1104]:
Fixed issue where the global refresher did not honor the config poll interval.


[[v1.0.1]]
=== Version 1.0.1 (8 June 2022)

Maintenance release.

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.0.1/index.html[API Reference]

==== Improvements

* https://issues.couchbase.com/browse/KCBC-79[KCBC-79]:
`JacksonJsonSerializer` now accepts the jackson `ObjectMapper` which for example makes it easier to use out of the box with Spring Boot.

* https://issues.couchbase.com/browse/JVMCBC-1093[JVMCBC-1093]:
Previously, when a DNS SRV lookup failure occurred, the SDK logged this as a `WARNING` along with a stack trace.
The lookup failure is typically harmless, so the log message has now been downgraded to `INFO` level, without a stack trace.

* https://issues.couchbase.com/browse/JVMCBC-1088[JVMCBC-1088]:
Updated Netty to version `4.1.77.Final`.


[[v1.0.0]]
=== Version 1.0.0 (3 May 2022)

Initial GA release.

//== Older Releases
//
//Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].

// end::all[]
