= Install and Start Using the Kotlin SDK with Couchbase Server
:navtitle: Start Using the SDK
:page-status: Developer Preview
include::project-docs:partial$attributes.adoc[]

[abstract]
A Kotlin application running on the JVM can use the Couchbase Kotlin SDK to access a Couchbase cluster.

The Couchbase Kotlin SDK is built on top of the same high performance I/O core as the Couchbase Java SDK.
It provides idiomatic Kotlin features like default arguments, suspend functions, and tasteful DSLs.

WARNING: These pages cover the _Developer Preview_ of the Couchbase Kotlin SDK 1.0.
Developer Preview code is likely to change without notice, and _should not_ be used in production.

== Installing the SDK

This guide assumes you are familiar with setting up a Kotlin project using Gradle or Maven.

The Couchbase Kotlin SDK requires Java 8 or later.
We recommend running the latest Java LTS version with the highest patch version available.

Couchbase publishes all stable artifacts to https://search.maven.org/search?q=com.couchbase.client[Maven Central].
The latest version (as of February 2022) is https://search.maven.org/artifact/com.couchbase.client/kotlin-client/{kotlin-current-version}/jar[{kotlin-current-version}].

You can use your favorite dependency management tool to include the SDK in your project.

[{tabs}]
====
Gradle (Kotlin)::
+
--
[source,kotlin,subs="+attributes"]
----
implementation("com.couchbase.client:kotlin-client:{kotlin-current-version}")
----

--
Gradle (Groovy)::
+
--
[source,groovy,subs="+attributes"]
----
implementation "com.couchbase.client:kotlin-client:{kotlin-current-version}"
----

--
Maven::
+
--
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.couchbase.client</groupId>
  <artifactId>kotlin-client</artifactId>
  <version>{kotlin-current-version}</version>
</dependency>
----
--
====

[snapshots]
== Using a Snapshot Version (optional)

Couchbase publishes pre-release snapshot artifacts to the Sonatype OSS Snapshot Repository.
If you wish to use a snapshot version, you'll need to tell your build tool about this repository.

[{tabs}]
====
Gradle (Kotlin)::
+
--
.`*build.gradle.kts*`
[source,kotlin]
----
repositories {
    mavenCentral()

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
        mavenContent { snapshotsOnly() }
    }
}
----

--
Gradle (Groovy)::
+
--
.`*build.gradle*`

[source,groovy]
----
repositories {
    mavenCentral()

    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
        mavenContent { snapshotsOnly() }
    }
}
----

--
Maven::
+
--
.`*pom.xml*`
[source,xml]
----
<repositories>
  <repository>
    <id>sonatype-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases><enabled>false</enabled></releases>
    <snapshots><enabled>true</enabled></snapshots>
  </repository>
</repositories>
----
--
====

== Hello Couchbase

Here's an example that demonstrates the simplest way to perform a N1QL query and get a document from the K/V service.

[{tabs}]
====
Local Couchbase Server::
+
--
[source,kotlin]
----
include::example$HelloWorld.kt[]
----
--

Couchbase Capella::
+
--
Connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella] is slightly different.
You'll need to configure the client to use TLS, and specify the trusted CA certificate used by the Couchbase deployment.

[source,kotlin]
----
include::example$HelloCloud.kt[]
----
--
====

More documentation and examples are coming in the future.
Meanwhile, please explore the https://github.com/couchbase/couchbase-jvm-clients/tree/master/kotlin-client/src/main/kotlin/com/couchbase/client/kotlin/samples[code samples on GitHub].

== Additional Resources

The API reference can be found {kotlin-api-link}[here].

Couchbase welcomes community contributions to the Kotlin SDK.
The Kotlin SDK source code is available on https://github.com/couchbase/couchbase-jvm-clients[GitHub].
