= Couchbase Kotlin SDK 1.1
:page-type: landing-page
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:!sectids:


++++
<div class="card-row two-column-row">
++++


[.column]
====== {empty}
[.content]
The Couchbase Kotlin client allows Kotlin applications to access a Couchbase cluster.
It offers synchronous APIs as well as reactive and asynchronous equivalents to maximize flexibility and performance.

[.column]
[.content]
[source,java]
----
include::hello-world:example$Overview.java[tag=overview,indent=0]
----

++++
</div>
++++



[.column]
====== {empty}

== Couchbase Kotlin SDK 1.1

++++
<div class="card-row three-column-row">
++++


[.column]
====== {empty}
.Getting Started

[.content]
* Dive right in with a xref:start-using-sdk.adoc[quick install and Hello World].
* Try out our xref:sample-application.adoc[Travel Sample Application].
* Compare and contrast with our xref:spring-data-sample-application.adoc[Spring Data sample App].

[.column]
====== {empty}
.Practical Howto Docs

[.content]
Connect to our services -- xref:howtos:kv-operations.adoc[data (KV)]; 
xref:howtos:n1ql-queries-with-sdk.adoc[Query]; 
xref:howtos:full-text-searching-with-sdk.adoc[Search]; 
xref:howtos:analytics-using-sdk.adoc[Analytics]; 
xref:howtos:view-queries-with-sdk.adoc[Views] -- 
and the xref:howtos:subdocument-operations.adoc[Sub-Document] and xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[transaction] APIs.

[.column]
====== {empty}
.Reference Guides

[.content]
The documentation supplements the practical Howto docs with references and xref:concept-docs:concepts.adoc[concept guides], for those who prefer a broader understanding before diving in and coding.

https://docs.couchbase.com/sdk-api/couchbase-kotlin-client/[API Docs^]


[.column]
====== {empty}
.What's Hot?

[.content]
Leverage the new Couchbase Server Scopes and Collection features to build multi-tenant micro-service application.
Integrate with Open Telemetry API to instrument telemetry data for your mission critical workloads that will make troubleshooting and debugging of your applications easier than ever.
Add an additional layer of security and protect your sensitive workloads using our Client Side Field Level Encryption capability. 

// Our xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[Distributed ACID Transactions] library is now integrated into the Kotlin SDK.

[.column]
====== {empty}
.About

[.content]
Those useful nuts-and-bolts guides to 
xref:project-docs:compatibility.adoc[compatibility tables]; 
xref:project-docs:sdk-release-notes.adoc[release notes]; and the 
xref:project-docs:get-involved.adoc[contribution guide].

[.column]
====== {empty}
.Community

[.content]
For community help, visit the https://forums.couchbase.com/c/kotlin-sdk/40[Couchbase forums^].
The Kotlin SDK can be combined with many other projects in the broader Kotlin and JVM ecosystem and beyond.
This includes xref:project-docs:compatibility.adoc#spring-compat[Spring Data] and xref:spark-connector::getting-started.adoc[Spark].
//  -- in the https://blog.couchbase.com/[Couchbase Blog^] there are examples covering everything from ????
[]
xref:project-docs:third-party-integrations.adoc[Integrations & Ecosystem]; 

++++
</div>
++++

include::7.1@sdk:shared:partial$archive.adoc[tag=link]
