= Install and Start Using the Kotlin SDK with Couchbase Server
:navtitle: Start Using the SDK
:page-status: Developer Preview

[abstract]
A Kotlin application running on the JVM can use the Couchbase Kotlin SDK to access a Couchbase cluster.

The Couchbase Kotlin SDK is built on top of the same high performance I/O core as the Couchbase Java SDK.
It provides idiomatic Kotlin features like default arguments, suspend functions, and tasteful DSLs.

WARNING: These pages cover the first _Developer Preview_ of the Couchbase Kotlin SDK 1.0 (DP1).
Developer Preview code is likely to change without notice, and _should not_ be used in production.

== Installing the SDK

This guide assumes you are familiar with setting up a Kotlin project using Maven or Gradle.

The Couchbase Kotlin SDK requires Java 8 or later.
We recommend running the latest Java LTS version with the highest patch version available.

Couchbase publishes all stable artifacts to https://search.maven.org/search?q=com.couchbase.client[Maven Central].
The latest version (as of July 2021) is https://search.maven.org/artifact/com.couchbase.client/couchbase-kotlin-client/1.0.0-dp.1/jar[1.0.0-dp.1].

You can use your favorite dependency management tool to install the SDK.
The following snippet shows how to do it with https://maven.apache.org/[Maven].

[source,xml]
----
<dependency>
  <groupId>com.couchbase.client</groupId>
  <artifactId>kotlin-client</artifactId>
  <version>1.0.0-dp.1</version>
</dependency>
----

For https://gradle.org/[Gradle], you can use:

[source,groovy]
----
implementation 'com.couchbase.client:kotlin-client:1.0.0-dp.1'
----

== Hello Couchbase

Here's an example that demonstrates the simplest way to perform a N1QL query and get a document from the K/V service.

[{tabs}]
====
Local Couchbase Server::
+
--
[source,kotlin]
----
include::example$HelloWorld.kt[]
----
--

Couchbase Cloud Sample::
+
--
Connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Cloud] is slightly different.
You'll need to configure the client to use TLS, and specify the trusted CA certificate used by the Couchbase deployment.

[source,kotlin]
----
include::example$HelloCloud.kt[]
----
--
====

More documentation and examples are coming in the future.
Meanwhile, please explore the https://github.com/couchbase/couchbase-jvm-clients/tree/master/kotlin-client/src/main/kotlin/com/couchbase/client/kotlin/samples[code samples on GitHub].

== Additional Resources

The API reference can be found https://docs.couchbase.com/sdk-api/couchbase-kotlin-client-1.0.0-dp.1/[here].

Couchbase welcomes community contributions to the Kotlin SDK.
The Kotlin SDK source code is available on https://github.com/couchbase/couchbase-jvm-clients[GitHub].
