= Hello World
:description: Install, connect, try. A quick start guide to get you up and running with Couchbase and the {name-sdk}.
:page-toc-levels: 3
:complete-code-include: include::devguide:example$kotlin/StartUsingCapella.kt[]
:page-partial:

[abstract]
{description}

The Couchbase Kotlin SDK is built on top of the same high performance I/O core as the Couchbase Java SDK.
It provides idiomatic Kotlin features like default arguments, suspend functions, and tasteful DSLs.


NOTE: From 3.9.0 on, all Couchbase JVM SDKs have an aligned version number to make it easier to users to track changes.
So the version then jumped from 1.5.x to 3.9.x.


// intro
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=intro]


// upsert snippet
.Upsert
[source,kotlin]
----
    collection.upsert(
        id = "alice",
        content = mapOf("favoriteColor" to "blue"),
    )
----


// intro-upsert
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=intro-upsert]


// TIP - DEE tutoral & Student record tutorial
// include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=other-tutorials]

TIP: This page walks you through a quick installation, and CRUD examples against the Data Service.
Elsewhere in this section you can find a fully worked-through xref:hello-world:sample-application.adoc[].


== Before You Start

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=before]



// Script the docs!
// Can any of the SDK installations be scripted?


=== Prerequisites

* You should know https://kotlinlang.org/docs/gradle.html[how to set up a new Kotlin project using Gradle] (or https://kotlinlang.org/docs/maven.html[using Maven]).
The SDK requires Kotlin 2.1.0 or later.

* You will need Java 8 or later.
We recommend running the latest Java LTS version with the highest patch version available.



// self-managed + Capella pre-reqs
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=prereq]



== Installation

All stable versions of the SDK are https://central.sonatype.com/artifact/com.couchbase.client/kotlin-client[available on Maven Central].

// tag::quick-install[]
You can use your favorite dependency management tool to include the SDK in your project.

[{tabs}]
====
Gradle (Kotlin)::
+
--
[source,kotlin,subs="+attributes"]
----
implementation("com.couchbase.client:kotlin-client:{sdk_current_version}")
----

--
Gradle (Groovy)::
+
--
[source,groovy,subs="+attributes"]
----
implementation "com.couchbase.client:kotlin-client:{sdk_current_version}"
----

--
Maven::
+
--
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.couchbase.client</groupId>
  <artifactId>kotlin-client</artifactId>
  <version>{sdk_current_version}</version>
</dependency>
----
--
====
// end::quick-install[]



////
[snapshots]
== Using a Snapshot Version (optional)

Couchbase publishes pre-release snapshot artifacts to the Central Portal Snapshots Repository.
If you wish to use a snapshot version, you'll need to tell your build tool about this repository.

[{tabs}]
====
Gradle (Kotlin)::
+
--
.`*build.gradle.kts*`
[source,kotlin]
----
repositories {
    mavenCentral()

    maven {
        url = uri("https://central.sonatype.com/repository/maven-snapshots/")
        mavenContent { snapshotsOnly() }
    }
}
----

--
Gradle (Groovy)::
+
--
.`*build.gradle*`

[source,groovy]
----
repositories {
    mavenCentral()

    maven {
        url "https://central.sonatype.com/repository/maven-snapshots/"
        mavenContent { snapshotsOnly() }
    }
}
----

--
Maven::
+
--
.`*pom.xml*`
[source,xml]
----
<repositories>
    <repository>
        <name>Central Portal Snapshots</name>
        <id>central-portal-snapshots</id>
        <url>https://central.sonatype.com/repository/maven-snapshots/</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
----
--
====
////





=== IDE Plugins

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=ide]


=== Grab the Code

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=complete-code]


== Connect to your Database

Connect to your Couchbase Capella operational cluster (or your local Couchbase Cluster, if you are trying out self-managed Couchbase).


[tabs,sync-group-id="Couchbase Capella|Self-Managed Couchbase Server"]
==== 
Couchbase Capella::
+
--
[source,kotlin]
----
    // Replace with your cluster address.
    val address = "--your-cluster--.cloud.couchbase.com"

    val cluster = Cluster.connect(
        connectionString = "couchbases://$address", 
        username = "username", // Replace with credentials
        password = "password", // of a database user account.
    )
----
--

Self-Managed Couchbase Server::
+
--

[source,kotlin]
----
    // Replace with your cluster address.
    val address = "127.0.0.1"

    val cluster = Cluster.connect(
        connectionString = "couchbases://$address", 
        username = "username", // Replace with credentials
        password = "password", // of a database user account.
    )
----
--

Cloud Native Gateway (CNG)::
+
--
Couchbase's large number of ports across the URLs of many services can be proxied by using a `couchbase2://` endpoint as the connection string --
currently only compatible with recent versions of xref:operator:ROOT:concept-cloud-native-gateway.adoc[Couchbase Autonomous Operator]:

[source,java]
----
val cluster = Cluster.connect(
  "couchbase2://10.12.14.16",
  ClusterOptions
    .create(username, password)
    .environment(env)
)
----

Read more on the xref:howtos:managing-connections.adoc#cloud-native-gateway[Connections] page.
--

Quarkus::
+
--
Our  xref:quarkus-extension:ROOT:overview.adoc[Couchbase Quarkus Java Extension docs] cover installing and connecting with the Quarkus extension in detail,
but if you already have Quarkus installed and a project ready (with `quarkus-couchbase` in your `pom.xml` or `build.gradle`),
then your `src/main/resources/application.properties` file needs to contain:

[source,properties]
----
quarkus.couchbase.connection-string=localhost
quarkus.couchbase.username=username
quarkus.couchbase.password=password
----
--
====

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=deeper-conn]


The `ClusterEnvironment.Builder` is covered more fully on the xref:ref:client-settings.adoc#the-environment-builder[Client Settings] page.


////
[TIP]
.Simpler Connection
====
There's also a simpler version of `Cluster.connect()` for when you don't need to customize the cluster environment:
[source,java]
----
include::devguide:example$java/SimpleConnect.java[tags=connect-string,indent=0]
----
====
////


=== Opening a Bucket

Following successful authentication, open the bucket with:

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=bucket,indent=0]
----



////
client has not yet completed bootstrapping (connecting to the cluster, getting the configuration, connecting to the nodes).
////


`waitUntilReady` is an optional call,
but it is good practice to use it.
Opening resources such as buckets is asynchronous --
that is, the `cluster.bucket` call returns immediately and proceeds in the background.
`waitUntilReady` ensures that the bucket resource is fully loaded before proceeding.
If not present, then the first key-value (KV) operation on the bucket will wait for it to be ready.
As with the earlier `Cluster.connect`, we use `.get` on the result here for simplicity.

*Collections* allow documents to be grouped by purpose or theme, according to a specified *scope* -- see data modeling, <<data-modeling,below>>.
Here we will use the `airport` collection within the `inventory` scope from `travel-sample` bucket as an example.

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=collection,indent=0]
----


== Create, Read, Update, Delete

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=crud]


=== JSON

We'll create a snippet of JSON to work with, using the client's own JSON library,
but you can read about the {name-sdk}'s support for other JSON libraries on the
xref:howtos:json.adoc[] page.

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=json,indent=0]
----

=== Insert (Create) and Upsert

`insert` and `upsert` will both create a new document.
The difference between the two is that if a document with that key already exists, the `insert` operation will fail,
// throwing `DocumentExistsException` --
while the `upsert` operation will succeed, replacing the content.

We need to provide a unique ID as the key, and we'll use a UUID here:

.Creating a new document
[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=upsert,indent=0]
----

=== Get (Read)

The `get` method reads a document from a collection.
// If the collection does not have a document with this ID, the `get` method also throws `DocumentNotFoundException`.

Wrapping the method in a `try` / `catch` is a good way to handle exceptions:

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=get,indent=0]
----

////
Here we're fetching the value for the key `docId`,
converting that value to a `JsonObjectSafe`
(a simple wrapper around `JsonObject` that returns `Try` results -- see
xref:howtos:json.adoc#error-handling-and-jsonobjectsafe[JsonObjectSafe] for details),
and then accessing the value of the *status* key as a String.
////

////
==== Better Error Handling

All three of these operations could fail, so there's quite a lot of error handling code here to do something quite simple.
One way to improve on this is by using `flatMap`, like this:

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=get-map,indent=0]
----

Alternatively, you can use a for-comprehension, like so:

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=get-for,indent=0]
----

Either of these methods will stop on the first failed operation.  So the final returned `Try` contains either 
a) `Success` and the result of the final operation, indicating that everything was successful, or 
b) `Failure` with the error returned by the first failing operation.
////

=== Replace (Update) and Overloads

////
You'll notice that most operations in the Scala SDK have two overloads.
One will take an Options builder, which provides all possible options that operation takes.
For instance:
////

.The replace method updates the value of an existing document
[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=replace-options,indent=0]
----

////
These options blocks are implemented as Scala case classes:
they are immutable data objects that return a copy of themselves on each change.

The other overload is provided purely for convenience.
It takes named arguments instead of an Options object, and provides only the most commonly used options:

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=replace-named,indent=0]
----
////

CAUTION: When you replace a document, it's usually good practice to use xref:howtos:kv-operations.adoc#optimistic-locking[optimistic locking].
Otherwise, changes might get lost if two people change the same document at the same time.

=== Remove (Delete)

The remove method deletes a document from a collection:

[source,java]
----
try {
  collection.remove("my-document");
} catch (DocumentNotFoundException ex) {
  System.out.println("Document did not exist when trying to remove");
}
----

Like `replace`, `remove` also optionally takes the xref:howtos:kv-operations.adoc#what-is-cas[CAS value] if you want to make sure you are only removing the document if it hasn’t changed since you last fetched it.


== Data Modeling

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=data-model]



== What Next?

////
Query and KV -
both
- but different emphasis on modelling objects....
////


include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=what-next]








////
== Hello Couchbase

Here's an example that shows how to execute a {sqlpp} (formerly N1QL) query and get a document from the Key Value (KV) service.

[{tabs}]
====
Couchbase Capella::
+
--
This version of the example assumes you are connecting to a https://docs.couchbase.com/cloud/index.html[Couchbase Capella] free tier operational cluster, which has the `travel-sample` bucket installed by default.

(If you're not using Couchbase Capella, click the **Local Couchbase Server** tab above.)

Before running the example:

* Replace the `address` variable with the address of your Capella cluster.

* Replace the `username` and `password` arguments with credentials for a cluster user that can read the `travel-sample` bucket.

[source,kotlin]
----
include::example$HelloCloud.kt[]
----
<1> For Capella, the connection string starts with `couchbases://` (note the final 's') to enable a secure connection with TLS.

--
Local Couchbase Server::
+
--

This version of the example assumes you are connecting to a single-node Couchbase Server cluster running on your local computer.

Before running the example:

* Install the `travel-sample` xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc[sample bucket].

* Replace the `username` and `password` arguments with credentials for a cluster user that can read the `travel-sample` bucket.
You can use the administrator credentials you chose when setting up the cluster.

[source,kotlin]
----
include::example$HelloWorld.kt[]
----
--

====



////
[TIP]
.Connecting to Cloud Native Gateway, for Kubernetes or OpenShift
====
Couchbase's large number of ports across the URLs of many services can be proxied by using a `couchbase2://` endpoint as the connection string -- read more on the xref:howtos:managing-connections.adoc#cloud-native-gateway[Connections] page.
====
////


[#additional-resources]
== Additional Resources

To see more documentation, select a chapter from the navigation sidebar on the left.

Join us on the https://discord.com/invite/sQ5qbPZuTh[Couchbase Discord server] and the https://forums.couchbase.com/c/kotlin-sdk/40[Couchbase Forum].

The https://couchbase.live[Couchbase Playground] has Kotlin examples you can edit and run in your web browser.

There are more https://github.com/couchbase/couchbase-jvm-clients/tree/master/kotlin-client/src/main/kotlin/com/couchbase/client/kotlin/samples[code samples on GitHub].

The API reference is {kotlin-api-link}[here].

Couchbase welcomes community contributions to the Kotlin SDK.
The source code is available on https://github.com/couchbase/couchbase-jvm-clients[GitHub].
////
